### ISSUE TITLE
UI exceed margin in Covid19 Outbreaks Dataset description

### ISSUE THREAD

**Issue by SwordFaith** [microsoft/openpaimarketplace#122]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/18397468/100328201-3b233700-3007-11eb-8f24-365b4d2b432a.png)

**Comment by debuggy** [comment]
Fixed in [last commit](https://github.com/microsoft/openpaimarketplace/commit/7cf8d151a94a1e39a51fd5ddc2e11528b0cd7f86)

https://github.com/microsoft/openpaimarketplace/commit/7cf8d151a94a1e39a51fd5ddc2e11528b0cd7f86
![image](https://user-images.githubusercontent.com/8444268/100416356-3a4add80-30b9-11eb-9ac0-2ffb036d1ac5.png)
